version: "3.9"
services:

  mabaya-db:
    image: mysql:8
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mabaya
    ports:
      - '3306:3306'
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./sql_scripts/:/var/www/html/sql_scripts
    networks:
      - mabaya-network

  mabaya-ad-service:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - mabaya-network
    env_file:
      - dev_env

networks:
  mabaya-network:
    name: default-mabaya