version: "3.9"
services:

  mabaya-db:
    image: mysql:8
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mabaya
    volumes:
      - ./sql_scripts/:/var/www/html/sql_scripts
    ports:
      - '3306:3306'
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - mabaya-network

networks:
  mabaya-network:
    name: default