mabaya:
  app:
    name: '@project.name@'
    version: '@project.version@'
  log:
    level: ${LOG_LEVEL}
  db:
    datasource:
      driverClassName: com.mysql.cj.jdbc.Driver
      minimum-idle: 1
      initialization-fail-timeout: 5000
spring:
  jmx:
    enabled: false
  main:
    banner-mode: off
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false